/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查（数据库、Gotenberg 连通性），供外部拨测使用 */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @description 各依赖的检查结果，值为 ok 或错误说明 */
            checks: {
                [key: string]: string;
            };
        };
        Error: {
            error: {
                /**
                 * @description 机器可读的错误码，如 validation_failed、not_found、unauthorized
                 * @example validation_failed
                 */
                code: string;
                /**
                 * @description 可直接展示给用户的中文说明
                 * @example 体温需在 34.0 到 43.0 之间
                 */
                message: string;
                /**
                 * @description 字段级错误，键为字段名
                 * @example {
                 *       "temperature": "out_of_range"
                 *     }
                 */
                fields?: {
                    [key: string]: string;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部依赖正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 至少一个依赖异常 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
