// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAccountSessions = `-- name: DeleteAccountSessions :execrows
DELETE FROM sessions WHERE account_id = $1
`

func (q *Queries) DeleteAccountSessions(ctx context.Context, accountID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountSessions, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFamily = `-- name: DeleteFamily :execrows
DELETE FROM families WHERE id = $1
`

func (q *Queries) DeleteFamily(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFamily, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const firstFamily = `-- name: FirstFamily :one
SELECT id, name, created_at, updated_at FROM families ORDER BY created_at LIMIT 1
`

func (q *Queries) FirstFamily(ctx context.Context) (Family, error) {
	row := q.db.QueryRow(ctx, firstFamily)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, password_hash, display_name, last_login_at, created_at, updated_at FROM accounts WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMe = `-- name: GetMe :one
SELECT a.id AS account_id, a.username, a.display_name, f.id AS family_id, f.name AS family_name
FROM accounts a
JOIN family_memberships fm ON fm.account_id = a.id
JOIN families f ON f.id = fm.family_id
WHERE a.id = $1 AND f.id = $2
`

type GetMeParams struct {
	AccountID uuid.UUID
	FamilyID  uuid.UUID
}

type GetMeRow struct {
	AccountID   uuid.UUID
	Username    string
	DisplayName string
	FamilyID    uuid.UUID
	FamilyName  string
}

func (q *Queries) GetMe(ctx context.Context, arg GetMeParams) (GetMeRow, error) {
	row := q.db.QueryRow(ctx, getMe, arg.AccountID, arg.FamilyID)
	var i GetMeRow
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.DisplayName,
		&i.FamilyID,
		&i.FamilyName,
	)
	return i, err
}

const getSessionPrincipal = `-- name: GetSessionPrincipal :one
SELECT s.id, s.account_id, s.expires_at, s.last_seen_at, fm.family_id
FROM sessions s
JOIN family_memberships fm ON fm.account_id = s.account_id
WHERE s.id = $1 AND s.expires_at > now()
ORDER BY fm.created_at
LIMIT 1
`

type GetSessionPrincipalRow struct {
	ID         []byte
	AccountID  uuid.UUID
	ExpiresAt  time.Time
	LastSeenAt time.Time
	FamilyID   uuid.UUID
}

func (q *Queries) GetSessionPrincipal(ctx context.Context, id []byte) (GetSessionPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getSessionPrincipal, id)
	var i GetSessionPrincipalRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.FamilyID,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (id, username, password_hash, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, username, password_hash, display_name, last_login_at, created_at, updated_at
`

type InsertAccountParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	DisplayName  string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFamily = `-- name: InsertFamily :one
INSERT INTO families (id, name) VALUES ($1, $2) RETURNING id, name, created_at, updated_at
`

type InsertFamilyParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) InsertFamily(ctx context.Context, arg InsertFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, insertFamily, arg.ID, arg.Name)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFamilyMembership = `-- name: InsertFamilyMembership :exec
INSERT INTO family_memberships (family_id, account_id, role) VALUES ($1, $2, 'owner')
`

type InsertFamilyMembershipParams struct {
	FamilyID  uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) InsertFamilyMembership(ctx context.Context, arg InsertFamilyMembershipParams) error {
	_, err := q.db.Exec(ctx, insertFamilyMembership, arg.FamilyID, arg.AccountID)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, account_id, expires_at, user_agent)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	ID        []byte
	AccountID uuid.UUID
	ExpiresAt time.Time
	UserAgent string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.AccountID,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	return err
}

const listFamilyStorageKeys = `-- name: ListFamilyStorageKeys :many
SELECT original_key, storage_key FROM attachments WHERE family_id = $1
`

type ListFamilyStorageKeysRow struct {
	OriginalKey string
	StorageKey  *string
}

func (q *Queries) ListFamilyStorageKeys(ctx context.Context, familyID uuid.UUID) ([]ListFamilyStorageKeysRow, error) {
	rows, err := q.db.Query(ctx, listFamilyStorageKeys, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFamilyStorageKeysRow
	for rows.Next() {
		var i ListFamilyStorageKeysRow
		if err := rows.Scan(&i.OriginalKey, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountPassword = `-- name: SetAccountPassword :execrows
UPDATE accounts SET password_hash = $1, updated_at = now() WHERE username = $2
`

type SetAccountPasswordParams struct {
	PasswordHash string
	Username     string
}

func (q *Queries) SetAccountPassword(ctx context.Context, arg SetAccountPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountPassword, arg.PasswordHash, arg.Username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAccountLogin = `-- name: TouchAccountLogin :exec
UPDATE accounts SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) TouchAccountLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAccountLogin, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), expires_at = $1, updated_at = now() WHERE id = $2
`

type TouchSessionParams struct {
	ExpiresAt time.Time
	ID        []byte
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ExpiresAt, arg.ID)
	return err
}
