// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countRecordPhotos = `-- name: CountRecordPhotos :one
SELECT count(*)::int FROM attachments WHERE record_id = $1 AND kind = 'photo'
`

func (q *Queries) CountRecordPhotos(ctx context.Context, recordID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countRecordPhotos, recordID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAttachment = `-- name: DeleteAttachment :one
DELETE FROM attachments WHERE family_id = $1 AND id = $2 RETURNING id, family_id, record_id, kind, status, original_key, storage_key, mime, size_bytes, duration_ms, width, height, caption, sort_order, created_at, updated_at
`

type DeleteAttachmentParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, deleteAttachment, arg.FamilyID, arg.ID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.RecordID,
		&i.Kind,
		&i.Status,
		&i.OriginalKey,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, family_id, record_id, kind, status, original_key, storage_key, mime, size_bytes, duration_ms, width, height, caption, sort_order, created_at, updated_at FROM attachments WHERE family_id = $1 AND id = $2
`

type GetAttachmentParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.FamilyID, arg.ID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.RecordID,
		&i.Kind,
		&i.Status,
		&i.OriginalKey,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttachmentAnyFamily = `-- name: GetAttachmentAnyFamily :one
SELECT id, family_id, record_id, kind, status, original_key, storage_key, mime, size_bytes, duration_ms, width, height, caption, sort_order, created_at, updated_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachmentAnyFamily(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentAnyFamily, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.RecordID,
		&i.Kind,
		&i.Status,
		&i.OriginalKey,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttachmentOwner = `-- name: GetAttachmentOwner :one
SELECT a.family_id, r.member_id AS record_member_id, r.episode_id AS record_episode_id
FROM attachments a
LEFT JOIN records r ON r.id = a.record_id
WHERE a.id = $1
`

type GetAttachmentOwnerRow struct {
	FamilyID        uuid.UUID
	RecordMemberID  *uuid.UUID
	RecordEpisodeID *uuid.UUID
}

func (q *Queries) GetAttachmentOwner(ctx context.Context, id uuid.UUID) (GetAttachmentOwnerRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentOwner, id)
	var i GetAttachmentOwnerRow
	err := row.Scan(&i.FamilyID, &i.RecordMemberID, &i.RecordEpisodeID)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO attachments (
    id, family_id, record_id, kind, status, original_key, storage_key, mime, size_bytes,
    duration_ms, width, height, caption, sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
ON CONFLICT (id) DO NOTHING
RETURNING id, family_id, record_id, kind, status, original_key, storage_key, mime, size_bytes, duration_ms, width, height, caption, sort_order, created_at, updated_at
`

type InsertAttachmentParams struct {
	ID          uuid.UUID
	FamilyID    uuid.UUID
	RecordID    *uuid.UUID
	Kind        AttachmentKind
	Status      AttachmentStatus
	OriginalKey string
	StorageKey  *string
	Mime        string
	SizeBytes   int64
	DurationMs  *int32
	Width       *int32
	Height      *int32
	Caption     *string
	SortOrder   int32
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.ID,
		arg.FamilyID,
		arg.RecordID,
		arg.Kind,
		arg.Status,
		arg.OriginalKey,
		arg.StorageKey,
		arg.Mime,
		arg.SizeBytes,
		arg.DurationMs,
		arg.Width,
		arg.Height,
		arg.Caption,
		arg.SortOrder,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.RecordID,
		&i.Kind,
		&i.Status,
		&i.OriginalKey,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttachmentsByRecords = `-- name: ListAttachmentsByRecords :many
SELECT id, family_id, record_id, kind, status, original_key, storage_key, mime, size_bytes, duration_ms, width, height, caption, sort_order, created_at, updated_at FROM attachments
WHERE family_id = $1 AND record_id = ANY($2::uuid[])
ORDER BY record_id, sort_order, created_at, id
`

type ListAttachmentsByRecordsParams struct {
	FamilyID  uuid.UUID
	RecordIds []uuid.UUID
}

func (q *Queries) ListAttachmentsByRecords(ctx context.Context, arg ListAttachmentsByRecordsParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByRecords, arg.FamilyID, arg.RecordIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.RecordID,
			&i.Kind,
			&i.Status,
			&i.OriginalKey,
			&i.StorageKey,
			&i.Mime,
			&i.SizeBytes,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.Caption,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaptionsByRecord = `-- name: ListCaptionsByRecord :many
SELECT caption FROM attachments WHERE record_id = $1 AND caption IS NOT NULL AND caption <> '' ORDER BY sort_order, created_at
`

func (q *Queries) ListCaptionsByRecord(ctx context.Context, recordID *uuid.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listCaptionsByRecord, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var caption *string
		if err := rows.Scan(&caption); err != nil {
			return nil, err
		}
		items = append(items, caption)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAttachmentSortOrder = `-- name: NextAttachmentSortOrder :one
SELECT COALESCE(max(sort_order) + 1, 0)::int FROM attachments WHERE record_id = $1
`

func (q *Queries) NextAttachmentSortOrder(ctx context.Context, recordID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextAttachmentSortOrder, recordID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setAttachmentProcessed = `-- name: SetAttachmentProcessed :exec
UPDATE attachments SET status = 'ready', storage_key = $1, mime = $2, duration_ms = $3, updated_at = now()
WHERE id = $4
`

type SetAttachmentProcessedParams struct {
	StorageKey *string
	Mime       string
	DurationMs *int32
	ID         uuid.UUID
}

func (q *Queries) SetAttachmentProcessed(ctx context.Context, arg SetAttachmentProcessedParams) error {
	_, err := q.db.Exec(ctx, setAttachmentProcessed,
		arg.StorageKey,
		arg.Mime,
		arg.DurationMs,
		arg.ID,
	)
	return err
}

const setAttachmentStatus = `-- name: SetAttachmentStatus :exec
UPDATE attachments SET status = $1, updated_at = now() WHERE id = $2
`

type SetAttachmentStatusParams struct {
	Status AttachmentStatus
	ID     uuid.UUID
}

func (q *Queries) SetAttachmentStatus(ctx context.Context, arg SetAttachmentStatusParams) error {
	_, err := q.db.Exec(ctx, setAttachmentStatus, arg.Status, arg.ID)
	return err
}

const updateAttachmentMeta = `-- name: UpdateAttachmentMeta :one
UPDATE attachments SET caption = $1, sort_order = $2, updated_at = now()
WHERE family_id = $3 AND id = $4
RETURNING id, family_id, record_id, kind, status, original_key, storage_key, mime, size_bytes, duration_ms, width, height, caption, sort_order, created_at, updated_at
`

type UpdateAttachmentMetaParams struct {
	Caption   *string
	SortOrder int32
	FamilyID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) UpdateAttachmentMeta(ctx context.Context, arg UpdateAttachmentMetaParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, updateAttachmentMeta,
		arg.Caption,
		arg.SortOrder,
		arg.FamilyID,
		arg.ID,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.RecordID,
		&i.Kind,
		&i.Status,
		&i.OriginalKey,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
