// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: episodes.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearFlareOutsideLong = `-- name: ClearFlareOutsideLong :exec
UPDATE records SET is_flare = false, updated_at = now()
WHERE family_id = $1 AND episode_id = $2 AND is_flare
`

type ClearFlareOutsideLongParams struct {
	FamilyID  uuid.UUID
	EpisodeID *uuid.UUID
}

func (q *Queries) ClearFlareOutsideLong(ctx context.Context, arg ClearFlareOutsideLongParams) error {
	_, err := q.db.Exec(ctx, clearFlareOutsideLong, arg.FamilyID, arg.EpisodeID)
	return err
}

const countEpisodesSince = `-- name: CountEpisodesSince :many
SELECT member_id, count(*)::int AS episode_count
FROM episodes
WHERE family_id = $1 AND member_id = ANY($2::uuid[])
  AND (ended_on IS NULL OR ended_on >= $3::date)
GROUP BY member_id
`

type CountEpisodesSinceParams struct {
	FamilyID  uuid.UUID
	MemberIds []uuid.UUID
	Since     time.Time
}

type CountEpisodesSinceRow struct {
	MemberID     uuid.UUID
	EpisodeCount int32
}

func (q *Queries) CountEpisodesSince(ctx context.Context, arg CountEpisodesSinceParams) ([]CountEpisodesSinceRow, error) {
	rows, err := q.db.Query(ctx, countEpisodesSince, arg.FamilyID, arg.MemberIds, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEpisodesSinceRow
	for rows.Next() {
		var i CountEpisodesSinceRow
		if err := rows.Scan(&i.MemberID, &i.EpisodeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEpisode = `-- name: DeleteEpisode :execrows
DELETE FROM episodes WHERE family_id = $1 AND id = $2
`

type DeleteEpisodeParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteEpisode(ctx context.Context, arg DeleteEpisodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEpisode, arg.FamilyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const episodeRecordStats = `-- name: EpisodeRecordStats :many
SELECT r.episode_id::uuid AS episode_id,
       bool_or(r.temperature IS NOT NULL) AS has_temperature,
       COALESCE(max(r.temperature), 0)::float8 AS max_temperature,
       count(*) FILTER (WHERE r.type = 'visit')::int AS visit_count,
       COALESCE(array_agg(DISTINCT r.med_name) FILTER (WHERE r.med_name IS NOT NULL), '{}')::text[] AS medications
FROM records r
WHERE r.family_id = $1 AND r.episode_id = ANY($2::uuid[])
GROUP BY r.episode_id
`

type EpisodeRecordStatsParams struct {
	FamilyID   uuid.UUID
	EpisodeIds []uuid.UUID
}

type EpisodeRecordStatsRow struct {
	EpisodeID      uuid.UUID
	HasTemperature bool
	MaxTemperature float64
	VisitCount     int32
	Medications    []string
}

func (q *Queries) EpisodeRecordStats(ctx context.Context, arg EpisodeRecordStatsParams) ([]EpisodeRecordStatsRow, error) {
	rows, err := q.db.Query(ctx, episodeRecordStats, arg.FamilyID, arg.EpisodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeRecordStatsRow
	for rows.Next() {
		var i EpisodeRecordStatsRow
		if err := rows.Scan(
			&i.EpisodeID,
			&i.HasTemperature,
			&i.MaxTemperature,
			&i.VisitCount,
			&i.Medications,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDiseaseTagByName = `-- name: FindDiseaseTagByName :one
SELECT id, family_id, name, created_at, updated_at FROM disease_tags
WHERE name = $1 AND (family_id IS NULL OR family_id = $2)
ORDER BY (family_id IS NOT NULL)
LIMIT 1
`

type FindDiseaseTagByNameParams struct {
	Name     string
	FamilyID *uuid.UUID
}

func (q *Queries) FindDiseaseTagByName(ctx context.Context, arg FindDiseaseTagByNameParams) (DiseaseTag, error) {
	row := q.db.QueryRow(ctx, findDiseaseTagByName, arg.Name, arg.FamilyID)
	var i DiseaseTag
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiseaseTag = `-- name: GetDiseaseTag :one
SELECT id, family_id, name, created_at, updated_at FROM disease_tags WHERE id = $1 AND (family_id IS NULL OR family_id = $2)
`

type GetDiseaseTagParams struct {
	ID       uuid.UUID
	FamilyID *uuid.UUID
}

func (q *Queries) GetDiseaseTag(ctx context.Context, arg GetDiseaseTagParams) (DiseaseTag, error) {
	row := q.db.QueryRow(ctx, getDiseaseTag, arg.ID, arg.FamilyID)
	var i DiseaseTag
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEpisode = `-- name: GetEpisode :one
SELECT e.id, e.family_id, e.member_id, e.disease_tag_id, e.name, e.kind, e.status, e.started_on, e.ended_on, e.created_at, e.updated_at, t.name AS disease_name,
       COALESCE(s.record_count, 0)::int AS record_count,
       COALESCE(s.last_record_at, 'epoch'::timestamptz)::timestamptz AS last_record_at,
       COALESCE(s.cost_total, 0)::bigint AS cost_total_cents
FROM episodes e
JOIN disease_tags t ON t.id = e.disease_tag_id
LEFT JOIN LATERAL (
    SELECT count(*) AS record_count, max(r.occurred_at) AS last_record_at, sum(r.cost_cents) AS cost_total
    FROM records r WHERE r.episode_id = e.id
) s ON true
WHERE e.family_id = $1 AND e.id = $2
`

type GetEpisodeParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

type GetEpisodeRow struct {
	Episode        Episode
	DiseaseName    string
	RecordCount    int32
	LastRecordAt   time.Time
	CostTotalCents int64
}

func (q *Queries) GetEpisode(ctx context.Context, arg GetEpisodeParams) (GetEpisodeRow, error) {
	row := q.db.QueryRow(ctx, getEpisode, arg.FamilyID, arg.ID)
	var i GetEpisodeRow
	err := row.Scan(
		&i.Episode.ID,
		&i.Episode.FamilyID,
		&i.Episode.MemberID,
		&i.Episode.DiseaseTagID,
		&i.Episode.Name,
		&i.Episode.Kind,
		&i.Episode.Status,
		&i.Episode.StartedOn,
		&i.Episode.EndedOn,
		&i.Episode.CreatedAt,
		&i.Episode.UpdatedAt,
		&i.DiseaseName,
		&i.RecordCount,
		&i.LastRecordAt,
		&i.CostTotalCents,
	)
	return i, err
}

const getEpisodeForUpdate = `-- name: GetEpisodeForUpdate :one
SELECT id, family_id, member_id, disease_tag_id, name, kind, status, started_on, ended_on, created_at, updated_at FROM episodes WHERE family_id = $1 AND id = $2 FOR UPDATE
`

type GetEpisodeForUpdateParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetEpisodeForUpdate(ctx context.Context, arg GetEpisodeForUpdateParams) (Episode, error) {
	row := q.db.QueryRow(ctx, getEpisodeForUpdate, arg.FamilyID, arg.ID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.MemberID,
		&i.DiseaseTagID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.StartedOn,
		&i.EndedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDiseaseTag = `-- name: InsertDiseaseTag :one
INSERT INTO disease_tags (id, family_id, name) VALUES ($1, $2, $3) RETURNING id, family_id, name, created_at, updated_at
`

type InsertDiseaseTagParams struct {
	ID       uuid.UUID
	FamilyID *uuid.UUID
	Name     string
}

func (q *Queries) InsertDiseaseTag(ctx context.Context, arg InsertDiseaseTagParams) (DiseaseTag, error) {
	row := q.db.QueryRow(ctx, insertDiseaseTag, arg.ID, arg.FamilyID, arg.Name)
	var i DiseaseTag
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEpisode = `-- name: InsertEpisode :one
INSERT INTO episodes (id, family_id, member_id, disease_tag_id, name, kind, status, started_on, ended_on)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, family_id, member_id, disease_tag_id, name, kind, status, started_on, ended_on, created_at, updated_at
`

type InsertEpisodeParams struct {
	ID           uuid.UUID
	FamilyID     uuid.UUID
	MemberID     uuid.UUID
	DiseaseTagID uuid.UUID
	Name         string
	Kind         EpisodeKind
	Status       EpisodeStatus
	StartedOn    time.Time
	EndedOn      *time.Time
}

func (q *Queries) InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, insertEpisode,
		arg.ID,
		arg.FamilyID,
		arg.MemberID,
		arg.DiseaseTagID,
		arg.Name,
		arg.Kind,
		arg.Status,
		arg.StartedOn,
		arg.EndedOn,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.MemberID,
		&i.DiseaseTagID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.StartedOn,
		&i.EndedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDiseaseTags = `-- name: ListDiseaseTags :many
SELECT id, family_id, name, created_at, updated_at FROM disease_tags
WHERE family_id IS NULL OR family_id = $1
ORDER BY (family_id IS NOT NULL), created_at, name
`

func (q *Queries) ListDiseaseTags(ctx context.Context, familyID *uuid.UUID) ([]DiseaseTag, error) {
	rows, err := q.db.Query(ctx, listDiseaseTags, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiseaseTag
	for rows.Next() {
		var i DiseaseTag
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT e.id, e.family_id, e.member_id, e.disease_tag_id, e.name, e.kind, e.status, e.started_on, e.ended_on, e.created_at, e.updated_at, t.name AS disease_name,
       COALESCE(s.record_count, 0)::int AS record_count,
       COALESCE(s.last_record_at, 'epoch'::timestamptz)::timestamptz AS last_record_at,
       COALESCE(s.cost_total, 0)::bigint AS cost_total_cents
FROM episodes e
JOIN disease_tags t ON t.id = e.disease_tag_id
LEFT JOIN LATERAL (
    SELECT count(*) AS record_count, max(r.occurred_at) AS last_record_at, sum(r.cost_cents) AS cost_total
    FROM records r WHERE r.episode_id = e.id
) s ON true
WHERE e.family_id = $1
  AND ($2::uuid IS NULL OR e.member_id = $2::uuid)
  AND ($3::uuid IS NULL OR e.disease_tag_id = $3::uuid)
  AND ($4::text IS NULL OR e.kind::text = $4::text)
  AND ($5::boolean IS NULL OR (e.status IN ('active', 'treating', 'stable')) = $5::boolean)
  AND ($6::date IS NULL OR e.ended_on IS NULL OR e.ended_on >= $6::date)
  AND ($7::date IS NULL OR e.started_on <= $7::date)
ORDER BY COALESCE(s.last_record_at, e.started_on::timestamptz) DESC, e.id DESC
`

type ListEpisodesParams struct {
	FamilyID     uuid.UUID
	MemberID     *uuid.UUID
	DiseaseTagID *uuid.UUID
	Kind         *string
	Open         *bool
	ActiveSince  *time.Time
	ActiveUntil  *time.Time
}

type ListEpisodesRow struct {
	Episode        Episode
	DiseaseName    string
	RecordCount    int32
	LastRecordAt   time.Time
	CostTotalCents int64
}

func (q *Queries) ListEpisodes(ctx context.Context, arg ListEpisodesParams) ([]ListEpisodesRow, error) {
	rows, err := q.db.Query(ctx, listEpisodes,
		arg.FamilyID,
		arg.MemberID,
		arg.DiseaseTagID,
		arg.Kind,
		arg.Open,
		arg.ActiveSince,
		arg.ActiveUntil,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpisodesRow
	for rows.Next() {
		var i ListEpisodesRow
		if err := rows.Scan(
			&i.Episode.ID,
			&i.Episode.FamilyID,
			&i.Episode.MemberID,
			&i.Episode.DiseaseTagID,
			&i.Episode.Name,
			&i.Episode.Kind,
			&i.Episode.Status,
			&i.Episode.StartedOn,
			&i.Episode.EndedOn,
			&i.Episode.CreatedAt,
			&i.Episode.UpdatedAt,
			&i.DiseaseName,
			&i.RecordCount,
			&i.LastRecordAt,
			&i.CostTotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLongEpisodeRefs = `-- name: ListLongEpisodeRefs :many
SELECT e.id, e.member_id, e.name, t.name AS disease_name, e.kind, e.status
FROM episodes e
JOIN disease_tags t ON t.id = e.disease_tag_id
WHERE e.family_id = $1 AND e.member_id = ANY($2::uuid[]) AND e.kind = 'long'
ORDER BY e.started_on, e.id
`

type ListLongEpisodeRefsParams struct {
	FamilyID  uuid.UUID
	MemberIds []uuid.UUID
}

type ListLongEpisodeRefsRow struct {
	ID          uuid.UUID
	MemberID    uuid.UUID
	Name        string
	DiseaseName string
	Kind        EpisodeKind
	Status      EpisodeStatus
}

func (q *Queries) ListLongEpisodeRefs(ctx context.Context, arg ListLongEpisodeRefsParams) ([]ListLongEpisodeRefsRow, error) {
	rows, err := q.db.Query(ctx, listLongEpisodeRefs, arg.FamilyID, arg.MemberIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLongEpisodeRefsRow
	for rows.Next() {
		var i ListLongEpisodeRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Name,
			&i.DiseaseName,
			&i.Kind,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpisode = `-- name: UpdateEpisode :one
UPDATE episodes SET
    disease_tag_id = $1,
    name = $2,
    kind = $3,
    status = $4,
    started_on = $5,
    ended_on = $6,
    updated_at = now()
WHERE family_id = $7 AND id = $8
RETURNING id, family_id, member_id, disease_tag_id, name, kind, status, started_on, ended_on, created_at, updated_at
`

type UpdateEpisodeParams struct {
	DiseaseTagID uuid.UUID
	Name         string
	Kind         EpisodeKind
	Status       EpisodeStatus
	StartedOn    time.Time
	EndedOn      *time.Time
	FamilyID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, updateEpisode,
		arg.DiseaseTagID,
		arg.Name,
		arg.Kind,
		arg.Status,
		arg.StartedOn,
		arg.EndedOn,
		arg.FamilyID,
		arg.ID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.MemberID,
		&i.DiseaseTagID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.StartedOn,
		&i.EndedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
