// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: families.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getFamily = `-- name: GetFamily :one
SELECT id, name, created_at, updated_at FROM families WHERE id = $1
`

func (q *Queries) GetFamily(ctx context.Context, id uuid.UUID) (Family, error) {
	row := q.db.QueryRow(ctx, getFamily, id)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
