// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs SET status = 'running', attempts = attempts + 1, updated_at = now()
WHERE id = (
    SELECT j.id FROM jobs j
    WHERE j.status = 'pending' AND j.run_after <= now()
    ORDER BY j.run_after, j.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, payload, status, attempts, run_after, last_error, created_at, updated_at
`

func (q *Queries) ClaimJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs SET status = 'done', last_error = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const deleteFinishedJobs = `-- name: DeleteFinishedJobs :execrows
DELETE FROM jobs WHERE status = 'done' AND updated_at < $1
`

func (q *Queries) DeleteFinishedJobs(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedJobs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :exec
INSERT INTO jobs (id, kind, payload, run_after) VALUES ($1, $2, $3, $4)
`

type EnqueueJobParams struct {
	ID       uuid.UUID
	Kind     string
	Payload  []byte
	RunAfter time.Time
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.Exec(ctx, enqueueJob,
		arg.ID,
		arg.Kind,
		arg.Payload,
		arg.RunAfter,
	)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET status = 'failed', last_error = $1, updated_at = now() WHERE id = $2
`

type FailJobParams struct {
	LastError *string
	ID        uuid.UUID
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.LastError, arg.ID)
	return err
}

const resetRunningJobs = `-- name: ResetRunningJobs :execrows
UPDATE jobs SET status = 'pending', updated_at = now() WHERE status = 'running'
`

func (q *Queries) ResetRunningJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetRunningJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs SET status = 'pending', run_after = $1, last_error = $2, updated_at = now() WHERE id = $3
`

type RetryJobParams struct {
	RunAfter  time.Time
	LastError *string
	ID        uuid.UUID
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.Exec(ctx, retryJob, arg.RunAfter, arg.LastError, arg.ID)
	return err
}
