// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAttachmentsByIDs = `-- name: DeleteAttachmentsByIDs :exec
DELETE FROM attachments WHERE family_id = $1 AND id = ANY($2::uuid[])
`

type DeleteAttachmentsByIDsParams struct {
	FamilyID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) DeleteAttachmentsByIDs(ctx context.Context, arg DeleteAttachmentsByIDsParams) error {
	_, err := q.db.Exec(ctx, deleteAttachmentsByIDs, arg.FamilyID, arg.Ids)
	return err
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM members WHERE family_id = $1 AND id = $2
`

type DeleteMemberParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMember, arg.FamilyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMember = `-- name: GetMember :one
SELECT id, family_id, nickname, relation, gender, birth_date, avatar_id, allergies, notes, blood_type, sort_order, archived_at, created_at, updated_at FROM members WHERE family_id = $1 AND id = $2
`

type GetMemberParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, arg.FamilyID, arg.ID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Nickname,
		&i.Relation,
		&i.Gender,
		&i.BirthDate,
		&i.AvatarID,
		&i.Allergies,
		&i.Notes,
		&i.BloodType,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberForUpdate = `-- name: GetMemberForUpdate :one
SELECT id, family_id, nickname, relation, gender, birth_date, avatar_id, allergies, notes, blood_type, sort_order, archived_at, created_at, updated_at FROM members WHERE family_id = $1 AND id = $2 FOR UPDATE
`

type GetMemberForUpdateParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetMemberForUpdate(ctx context.Context, arg GetMemberForUpdateParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberForUpdate, arg.FamilyID, arg.ID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Nickname,
		&i.Relation,
		&i.Gender,
		&i.BirthDate,
		&i.AvatarID,
		&i.Allergies,
		&i.Notes,
		&i.BloodType,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :one
INSERT INTO members (id, family_id, nickname, relation, gender, birth_date, avatar_id, allergies, notes, blood_type, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, family_id, nickname, relation, gender, birth_date, avatar_id, allergies, notes, blood_type, sort_order, archived_at, created_at, updated_at
`

type InsertMemberParams struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	Nickname  string
	Relation  MemberRelation
	Gender    MemberGender
	BirthDate time.Time
	AvatarID  *uuid.UUID
	Allergies *string
	Notes     *string
	BloodType *BloodType
	SortOrder int32
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, insertMember,
		arg.ID,
		arg.FamilyID,
		arg.Nickname,
		arg.Relation,
		arg.Gender,
		arg.BirthDate,
		arg.AvatarID,
		arg.Allergies,
		arg.Notes,
		arg.BloodType,
		arg.SortOrder,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Nickname,
		&i.Relation,
		&i.Gender,
		&i.BirthDate,
		&i.AvatarID,
		&i.Allergies,
		&i.Notes,
		&i.BloodType,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemberStorageKeys = `-- name: ListMemberStorageKeys :many
SELECT a.id, a.original_key, a.storage_key
FROM attachments a
LEFT JOIN records r ON r.id = a.record_id
WHERE a.family_id = $1
  AND (r.member_id = $2 OR a.id = (SELECT m.avatar_id FROM members m WHERE m.family_id = $1 AND m.id = $2))
`

type ListMemberStorageKeysParams struct {
	FamilyID uuid.UUID
	MemberID uuid.UUID
}

type ListMemberStorageKeysRow struct {
	ID          uuid.UUID
	OriginalKey string
	StorageKey  *string
}

func (q *Queries) ListMemberStorageKeys(ctx context.Context, arg ListMemberStorageKeysParams) ([]ListMemberStorageKeysRow, error) {
	rows, err := q.db.Query(ctx, listMemberStorageKeys, arg.FamilyID, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberStorageKeysRow
	for rows.Next() {
		var i ListMemberStorageKeysRow
		if err := rows.Scan(&i.ID, &i.OriginalKey, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT id, family_id, nickname, relation, gender, birth_date, avatar_id, allergies, notes, blood_type, sort_order, archived_at, created_at, updated_at FROM members
WHERE family_id = $1 AND ($2::boolean OR archived_at IS NULL)
ORDER BY sort_order, created_at
`

type ListMembersParams struct {
	FamilyID        uuid.UUID
	IncludeArchived bool
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.FamilyID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Nickname,
			&i.Relation,
			&i.Gender,
			&i.BirthDate,
			&i.AvatarID,
			&i.Allergies,
			&i.Notes,
			&i.BloodType,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMemberSortOrder = `-- name: NextMemberSortOrder :one
SELECT COALESCE(max(sort_order) + 1, 0)::int FROM members WHERE family_id = $1
`

func (q *Queries) NextMemberSortOrder(ctx context.Context, familyID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextMemberSortOrder, familyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setMemberArchived = `-- name: SetMemberArchived :one
UPDATE members SET archived_at = $1, updated_at = now()
WHERE family_id = $2 AND id = $3
RETURNING id, family_id, nickname, relation, gender, birth_date, avatar_id, allergies, notes, blood_type, sort_order, archived_at, created_at, updated_at
`

type SetMemberArchivedParams struct {
	ArchivedAt *time.Time
	FamilyID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) SetMemberArchived(ctx context.Context, arg SetMemberArchivedParams) (Member, error) {
	row := q.db.QueryRow(ctx, setMemberArchived, arg.ArchivedAt, arg.FamilyID, arg.ID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Nickname,
		&i.Relation,
		&i.Gender,
		&i.BirthDate,
		&i.AvatarID,
		&i.Allergies,
		&i.Notes,
		&i.BloodType,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMember = `-- name: UpdateMember :one
UPDATE members SET
    nickname = $1,
    relation = $2,
    gender = $3,
    birth_date = $4,
    avatar_id = $5,
    allergies = $6,
    notes = $7,
    blood_type = $8,
    sort_order = $9,
    updated_at = now()
WHERE family_id = $10 AND id = $11
RETURNING id, family_id, nickname, relation, gender, birth_date, avatar_id, allergies, notes, blood_type, sort_order, archived_at, created_at, updated_at
`

type UpdateMemberParams struct {
	Nickname  string
	Relation  MemberRelation
	Gender    MemberGender
	BirthDate time.Time
	AvatarID  *uuid.UUID
	Allergies *string
	Notes     *string
	BloodType *BloodType
	SortOrder int32
	FamilyID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.Nickname,
		arg.Relation,
		arg.Gender,
		arg.BirthDate,
		arg.AvatarID,
		arg.Allergies,
		arg.Notes,
		arg.BloodType,
		arg.SortOrder,
		arg.FamilyID,
		arg.ID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Nickname,
		&i.Relation,
		&i.Gender,
		&i.BirthDate,
		&i.AvatarID,
		&i.Allergies,
		&i.Notes,
		&i.BloodType,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
