// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AttachmentKind string

const (
	AttachmentKindPhoto  AttachmentKind = "photo"
	AttachmentKindAudio  AttachmentKind = "audio"
	AttachmentKindAvatar AttachmentKind = "avatar"
)

func (e *AttachmentKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttachmentKind(s)
	case string:
		*e = AttachmentKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AttachmentKind: %T", src)
	}
	return nil
}

type NullAttachmentKind struct {
	AttachmentKind AttachmentKind
	Valid          bool // Valid is true if AttachmentKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttachmentKind) Scan(value interface{}) error {
	if value == nil {
		ns.AttachmentKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttachmentKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttachmentKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttachmentKind), nil
}

func (e AttachmentKind) Valid() bool {
	switch e {
	case AttachmentKindPhoto,
		AttachmentKindAudio,
		AttachmentKindAvatar:
		return true
	}
	return false
}

func AllAttachmentKindValues() []AttachmentKind {
	return []AttachmentKind{
		AttachmentKindPhoto,
		AttachmentKindAudio,
		AttachmentKindAvatar,
	}
}

type AttachmentStatus string

const (
	AttachmentStatusPending    AttachmentStatus = "pending"
	AttachmentStatusProcessing AttachmentStatus = "processing"
	AttachmentStatusReady      AttachmentStatus = "ready"
	AttachmentStatusFailed     AttachmentStatus = "failed"
)

func (e *AttachmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttachmentStatus(s)
	case string:
		*e = AttachmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AttachmentStatus: %T", src)
	}
	return nil
}

type NullAttachmentStatus struct {
	AttachmentStatus AttachmentStatus
	Valid            bool // Valid is true if AttachmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttachmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AttachmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttachmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttachmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttachmentStatus), nil
}

func (e AttachmentStatus) Valid() bool {
	switch e {
	case AttachmentStatusPending,
		AttachmentStatusProcessing,
		AttachmentStatusReady,
		AttachmentStatusFailed:
		return true
	}
	return false
}

func AllAttachmentStatusValues() []AttachmentStatus {
	return []AttachmentStatus{
		AttachmentStatusPending,
		AttachmentStatusProcessing,
		AttachmentStatusReady,
		AttachmentStatusFailed,
	}
}

type BloodType string

const (
	BloodTypeA       BloodType = "A"
	BloodTypeB       BloodType = "B"
	BloodTypeAB      BloodType = "AB"
	BloodTypeO       BloodType = "O"
	BloodTypeUnknown BloodType = "unknown"
)

func (e *BloodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BloodType(s)
	case string:
		*e = BloodType(s)
	default:
		return fmt.Errorf("unsupported scan type for BloodType: %T", src)
	}
	return nil
}

type NullBloodType struct {
	BloodType BloodType
	Valid     bool // Valid is true if BloodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBloodType) Scan(value interface{}) error {
	if value == nil {
		ns.BloodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BloodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBloodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BloodType), nil
}

func (e BloodType) Valid() bool {
	switch e {
	case BloodTypeA,
		BloodTypeB,
		BloodTypeAB,
		BloodTypeO,
		BloodTypeUnknown:
		return true
	}
	return false
}

func AllBloodTypeValues() []BloodType {
	return []BloodType{
		BloodTypeA,
		BloodTypeB,
		BloodTypeAB,
		BloodTypeO,
		BloodTypeUnknown,
	}
}

type EpisodeKind string

const (
	EpisodeKindShort EpisodeKind = "short"
	EpisodeKindLong  EpisodeKind = "long"
)

func (e *EpisodeKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EpisodeKind(s)
	case string:
		*e = EpisodeKind(s)
	default:
		return fmt.Errorf("unsupported scan type for EpisodeKind: %T", src)
	}
	return nil
}

type NullEpisodeKind struct {
	EpisodeKind EpisodeKind
	Valid       bool // Valid is true if EpisodeKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEpisodeKind) Scan(value interface{}) error {
	if value == nil {
		ns.EpisodeKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EpisodeKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEpisodeKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EpisodeKind), nil
}

func (e EpisodeKind) Valid() bool {
	switch e {
	case EpisodeKindShort,
		EpisodeKindLong:
		return true
	}
	return false
}

func AllEpisodeKindValues() []EpisodeKind {
	return []EpisodeKind{
		EpisodeKindShort,
		EpisodeKindLong,
	}
}

type EpisodeStatus string

const (
	EpisodeStatusActive    EpisodeStatus = "active"
	EpisodeStatusRecovered EpisodeStatus = "recovered"
	EpisodeStatusTreating  EpisodeStatus = "treating"
	EpisodeStatusStable    EpisodeStatus = "stable"
	EpisodeStatusEnded     EpisodeStatus = "ended"
)

func (e *EpisodeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EpisodeStatus(s)
	case string:
		*e = EpisodeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EpisodeStatus: %T", src)
	}
	return nil
}

type NullEpisodeStatus struct {
	EpisodeStatus EpisodeStatus
	Valid         bool // Valid is true if EpisodeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEpisodeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EpisodeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EpisodeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEpisodeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EpisodeStatus), nil
}

func (e EpisodeStatus) Valid() bool {
	switch e {
	case EpisodeStatusActive,
		EpisodeStatusRecovered,
		EpisodeStatusTreating,
		EpisodeStatusStable,
		EpisodeStatusEnded:
		return true
	}
	return false
}

func AllEpisodeStatusValues() []EpisodeStatus {
	return []EpisodeStatus{
		EpisodeStatusActive,
		EpisodeStatusRecovered,
		EpisodeStatusTreating,
		EpisodeStatusStable,
		EpisodeStatusEnded,
	}
}

type JobStatus string

const (
	JobStatusPending JobStatus = "pending"
	JobStatusRunning JobStatus = "running"
	JobStatusDone    JobStatus = "done"
	JobStatusFailed  JobStatus = "failed"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusPending,
		JobStatusRunning,
		JobStatusDone,
		JobStatusFailed:
		return true
	}
	return false
}

func AllJobStatusValues() []JobStatus {
	return []JobStatus{
		JobStatusPending,
		JobStatusRunning,
		JobStatusDone,
		JobStatusFailed,
	}
}

type MemberGender string

const (
	MemberGenderMale   MemberGender = "male"
	MemberGenderFemale MemberGender = "female"
)

func (e *MemberGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberGender(s)
	case string:
		*e = MemberGender(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberGender: %T", src)
	}
	return nil
}

type NullMemberGender struct {
	MemberGender MemberGender
	Valid        bool // Valid is true if MemberGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberGender) Scan(value interface{}) error {
	if value == nil {
		ns.MemberGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberGender), nil
}

func (e MemberGender) Valid() bool {
	switch e {
	case MemberGenderMale,
		MemberGenderFemale:
		return true
	}
	return false
}

func AllMemberGenderValues() []MemberGender {
	return []MemberGender{
		MemberGenderMale,
		MemberGenderFemale,
	}
}

type MemberRelation string

const (
	MemberRelationSelf        MemberRelation = "self"
	MemberRelationSpouse      MemberRelation = "spouse"
	MemberRelationChild       MemberRelation = "child"
	MemberRelationParent      MemberRelation = "parent"
	MemberRelationGrandparent MemberRelation = "grandparent"
	MemberRelationOther       MemberRelation = "other"
)

func (e *MemberRelation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRelation(s)
	case string:
		*e = MemberRelation(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRelation: %T", src)
	}
	return nil
}

type NullMemberRelation struct {
	MemberRelation MemberRelation
	Valid          bool // Valid is true if MemberRelation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRelation) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRelation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRelation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRelation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRelation), nil
}

func (e MemberRelation) Valid() bool {
	switch e {
	case MemberRelationSelf,
		MemberRelationSpouse,
		MemberRelationChild,
		MemberRelationParent,
		MemberRelationGrandparent,
		MemberRelationOther:
		return true
	}
	return false
}

func AllMemberRelationValues() []MemberRelation {
	return []MemberRelation{
		MemberRelationSelf,
		MemberRelationSpouse,
		MemberRelationChild,
		MemberRelationParent,
		MemberRelationGrandparent,
		MemberRelationOther,
	}
}

type RecordType string

const (
	RecordTypeSymptom     RecordType = "symptom"
	RecordTypeTemperature RecordType = "temperature"
	RecordTypeMedication  RecordType = "medication"
	RecordTypeVisit       RecordType = "visit"
	RecordTypeTreatment   RecordType = "treatment"
	RecordTypeExam        RecordType = "exam"
	RecordTypeOther       RecordType = "other"
)

func (e *RecordType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordType(s)
	case string:
		*e = RecordType(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordType: %T", src)
	}
	return nil
}

type NullRecordType struct {
	RecordType RecordType
	Valid      bool // Valid is true if RecordType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordType) Scan(value interface{}) error {
	if value == nil {
		ns.RecordType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordType), nil
}

func (e RecordType) Valid() bool {
	switch e {
	case RecordTypeSymptom,
		RecordTypeTemperature,
		RecordTypeMedication,
		RecordTypeVisit,
		RecordTypeTreatment,
		RecordTypeExam,
		RecordTypeOther:
		return true
	}
	return false
}

func AllRecordTypeValues() []RecordType {
	return []RecordType{
		RecordTypeSymptom,
		RecordTypeTemperature,
		RecordTypeMedication,
		RecordTypeVisit,
		RecordTypeTreatment,
		RecordTypeExam,
		RecordTypeOther,
	}
}

type Account struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	DisplayName  string
	LastLoginAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Attachment struct {
	ID          uuid.UUID
	FamilyID    uuid.UUID
	RecordID    *uuid.UUID
	Kind        AttachmentKind
	Status      AttachmentStatus
	OriginalKey string
	StorageKey  *string
	Mime        string
	SizeBytes   int64
	DurationMs  *int32
	Width       *int32
	Height      *int32
	Caption     *string
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DiseaseTag struct {
	ID        uuid.UUID
	FamilyID  *uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Episode struct {
	ID           uuid.UUID
	FamilyID     uuid.UUID
	MemberID     uuid.UUID
	DiseaseTagID uuid.UUID
	Name         string
	Kind         EpisodeKind
	Status       EpisodeStatus
	StartedOn    pgtype.Date
	EndedOn      pgtype.Date
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Family struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FamilyMembership struct {
	FamilyID  uuid.UUID
	AccountID uuid.UUID
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Job struct {
	ID        uuid.UUID
	Kind      string
	Payload   []byte
	Status    JobStatus
	Attempts  int32
	RunAfter  time.Time
	LastError *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Member struct {
	ID         uuid.UUID
	FamilyID   uuid.UUID
	Nickname   string
	Relation   MemberRelation
	Gender     MemberGender
	BirthDate  pgtype.Date
	AvatarID   *uuid.UUID
	Allergies  *string
	Notes      *string
	BloodType  *BloodType
	SortOrder  int32
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Record struct {
	ID          uuid.UUID
	FamilyID    uuid.UUID
	MemberID    uuid.UUID
	EpisodeID   *uuid.UUID
	Type        *RecordType
	OccurredAt  time.Time
	Body        string
	IsFlare     bool
	Severity    *int16
	Temperature pgtype.Numeric
	MedName     *string
	MedDose     pgtype.Numeric
	MedUnit     *string
	CostCents   *int32
	Details     []byte
	SearchText  string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	ID         []byte
	AccountID  uuid.UUID
	ExpiresAt  time.Time
	LastSeenAt time.Time
	UserAgent  string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
