// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignRecords = `-- name: AssignRecords :execrows
UPDATE records SET
    episode_id = $1::uuid,
    is_flare = is_flare AND $2::boolean,
    updated_at = now()
WHERE family_id = $3 AND id = ANY($4::uuid[])
`

type AssignRecordsParams struct {
	EpisodeID *uuid.UUID
	KeepFlare bool
	FamilyID  uuid.UUID
	Ids       []uuid.UUID
}

func (q *Queries) AssignRecords(ctx context.Context, arg AssignRecordsParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignRecords,
		arg.EpisodeID,
		arg.KeepFlare,
		arg.FamilyID,
		arg.Ids,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const calendarDays = `-- name: CalendarDays :many
SELECT (r.occurred_at AT TIME ZONE $1::text)::date AS day,
       count(*) FILTER (WHERE r.type = 'symptom')::int AS symptom,
       count(*) FILTER (WHERE r.type = 'temperature')::int AS temperature,
       count(*) FILTER (WHERE r.type = 'medication')::int AS medication,
       count(*) FILTER (WHERE r.type = 'visit')::int AS visit,
       count(*) FILTER (WHERE r.type = 'treatment')::int AS treatment,
       count(*) FILTER (WHERE r.type = 'exam')::int AS exam,
       count(*) FILTER (WHERE r.type = 'other')::int AS other,
       count(*) FILTER (WHERE r.type IS NULL)::int AS untyped,
       COALESCE(max(r.severity), -1)::int AS max_severity,
       bool_or(r.is_flare) AS flare
FROM records r
WHERE r.family_id = $2
  AND ($3::uuid IS NULL OR r.episode_id = $3::uuid)
  AND ($4::uuid IS NULL OR r.member_id = $4::uuid)
  AND r.occurred_at >= $5 AND r.occurred_at < $6
GROUP BY 1
ORDER BY 1
`

type CalendarDaysParams struct {
	Tz        string
	FamilyID  uuid.UUID
	EpisodeID *uuid.UUID
	MemberID  *uuid.UUID
	FromTime  time.Time
	ToTime    time.Time
}

type CalendarDaysRow struct {
	Day         time.Time
	Symptom     int32
	Temperature int32
	Medication  int32
	Visit       int32
	Treatment   int32
	Exam        int32
	Other       int32
	Untyped     int32
	MaxSeverity int32
	Flare       bool
}

func (q *Queries) CalendarDays(ctx context.Context, arg CalendarDaysParams) ([]CalendarDaysRow, error) {
	rows, err := q.db.Query(ctx, calendarDays,
		arg.Tz,
		arg.FamilyID,
		arg.EpisodeID,
		arg.MemberID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarDaysRow
	for rows.Next() {
		var i CalendarDaysRow
		if err := rows.Scan(
			&i.Day,
			&i.Symptom,
			&i.Temperature,
			&i.Medication,
			&i.Visit,
			&i.Treatment,
			&i.Exam,
			&i.Other,
			&i.Untyped,
			&i.MaxSeverity,
			&i.Flare,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calendarDaysByEpisodes = `-- name: CalendarDaysByEpisodes :many
SELECT r.episode_id::uuid AS episode_id,
       (r.occurred_at AT TIME ZONE $1::text)::date AS day,
       count(*) FILTER (WHERE r.type = 'symptom')::int AS symptom,
       count(*) FILTER (WHERE r.type = 'temperature')::int AS temperature,
       count(*) FILTER (WHERE r.type = 'medication')::int AS medication,
       count(*) FILTER (WHERE r.type = 'visit')::int AS visit,
       count(*) FILTER (WHERE r.type = 'treatment')::int AS treatment,
       count(*) FILTER (WHERE r.type = 'exam')::int AS exam,
       count(*) FILTER (WHERE r.type = 'other')::int AS other,
       count(*) FILTER (WHERE r.type IS NULL)::int AS untyped,
       COALESCE(max(r.severity), -1)::int AS max_severity,
       bool_or(r.is_flare) AS flare
FROM records r
WHERE r.family_id = $2 AND r.episode_id = ANY($3::uuid[])
  AND r.occurred_at >= $4 AND r.occurred_at < $5
GROUP BY 1, 2
ORDER BY 1, 2
`

type CalendarDaysByEpisodesParams struct {
	Tz         string
	FamilyID   uuid.UUID
	EpisodeIds []uuid.UUID
	FromTime   time.Time
	ToTime     time.Time
}

type CalendarDaysByEpisodesRow struct {
	EpisodeID   uuid.UUID
	Day         time.Time
	Symptom     int32
	Temperature int32
	Medication  int32
	Visit       int32
	Treatment   int32
	Exam        int32
	Other       int32
	Untyped     int32
	MaxSeverity int32
	Flare       bool
}

func (q *Queries) CalendarDaysByEpisodes(ctx context.Context, arg CalendarDaysByEpisodesParams) ([]CalendarDaysByEpisodesRow, error) {
	rows, err := q.db.Query(ctx, calendarDaysByEpisodes,
		arg.Tz,
		arg.FamilyID,
		arg.EpisodeIds,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarDaysByEpisodesRow
	for rows.Next() {
		var i CalendarDaysByEpisodesRow
		if err := rows.Scan(
			&i.EpisodeID,
			&i.Day,
			&i.Symptom,
			&i.Temperature,
			&i.Medication,
			&i.Visit,
			&i.Treatment,
			&i.Exam,
			&i.Other,
			&i.Untyped,
			&i.MaxSeverity,
			&i.Flare,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countInbox = `-- name: CountInbox :one
SELECT count(*)::int FROM records WHERE family_id = $1 AND episode_id IS NULL
`

func (q *Queries) CountInbox(ctx context.Context, familyID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countInbox, familyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteRecord = `-- name: DeleteRecord :execrows
DELETE FROM records WHERE family_id = $1 AND id = $2
`

type DeleteRecordParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecord, arg.FamilyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRecord = `-- name: GetRecord :one
SELECT id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at FROM records WHERE family_id = $1 AND id = $2
`

type GetRecordParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetRecord(ctx context.Context, arg GetRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, getRecord, arg.FamilyID, arg.ID)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.MemberID,
		&i.EpisodeID,
		&i.Type,
		&i.OccurredAt,
		&i.Body,
		&i.IsFlare,
		&i.Severity,
		&i.Temperature,
		&i.MedName,
		&i.MedDose,
		&i.MedUnit,
		&i.CostCents,
		&i.Details,
		&i.SearchText,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecordFamily = `-- name: GetRecordFamily :one
SELECT family_id FROM records WHERE id = $1
`

func (q *Queries) GetRecordFamily(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRecordFamily, id)
	var family_id uuid.UUID
	err := row.Scan(&family_id)
	return family_id, err
}

const getRecordForUpdate = `-- name: GetRecordForUpdate :one
SELECT id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at FROM records WHERE family_id = $1 AND id = $2 FOR UPDATE
`

type GetRecordForUpdateParams struct {
	FamilyID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetRecordForUpdate(ctx context.Context, arg GetRecordForUpdateParams) (Record, error) {
	row := q.db.QueryRow(ctx, getRecordForUpdate, arg.FamilyID, arg.ID)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.MemberID,
		&i.EpisodeID,
		&i.Type,
		&i.OccurredAt,
		&i.Body,
		&i.IsFlare,
		&i.Severity,
		&i.Temperature,
		&i.MedName,
		&i.MedDose,
		&i.MedUnit,
		&i.CostCents,
		&i.Details,
		&i.SearchText,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecord = `-- name: InsertRecord :one
INSERT INTO records (
    id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature,
    med_name, med_dose, med_unit, cost_cents, details, search_text, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17
)
ON CONFLICT (id) DO NOTHING
RETURNING id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at
`

type InsertRecordParams struct {
	ID          uuid.UUID
	FamilyID    uuid.UUID
	MemberID    uuid.UUID
	EpisodeID   *uuid.UUID
	Type        *RecordType
	OccurredAt  time.Time
	Body        string
	IsFlare     bool
	Severity    *int16
	Temperature *float64
	MedName     *string
	MedDose     *float64
	MedUnit     *string
	CostCents   *int32
	Details     []byte
	SearchText  string
	CreatedBy   *uuid.UUID
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, insertRecord,
		arg.ID,
		arg.FamilyID,
		arg.MemberID,
		arg.EpisodeID,
		arg.Type,
		arg.OccurredAt,
		arg.Body,
		arg.IsFlare,
		arg.Severity,
		arg.Temperature,
		arg.MedName,
		arg.MedDose,
		arg.MedUnit,
		arg.CostCents,
		arg.Details,
		arg.SearchText,
		arg.CreatedBy,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.MemberID,
		&i.EpisodeID,
		&i.Type,
		&i.OccurredAt,
		&i.Body,
		&i.IsFlare,
		&i.Severity,
		&i.Temperature,
		&i.MedName,
		&i.MedDose,
		&i.MedUnit,
		&i.CostCents,
		&i.Details,
		&i.SearchText,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastMedication = `-- name: LastMedication :one
SELECT id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at FROM records
WHERE family_id = $1 AND member_id = $2 AND type = 'medication'
  AND med_name = $3 AND occurred_at <= now()
ORDER BY occurred_at DESC, id DESC
LIMIT 1
`

type LastMedicationParams struct {
	FamilyID uuid.UUID
	MemberID uuid.UUID
	MedName  *string
}

func (q *Queries) LastMedication(ctx context.Context, arg LastMedicationParams) (Record, error) {
	row := q.db.QueryRow(ctx, lastMedication, arg.FamilyID, arg.MemberID, arg.MedName)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.MemberID,
		&i.EpisodeID,
		&i.Type,
		&i.OccurredAt,
		&i.Body,
		&i.IsFlare,
		&i.Severity,
		&i.Temperature,
		&i.MedName,
		&i.MedDose,
		&i.MedUnit,
		&i.CostCents,
		&i.Details,
		&i.SearchText,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestMedicationByEpisodes = `-- name: LatestMedicationByEpisodes :many
SELECT DISTINCT ON (episode_id) id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at FROM records
WHERE family_id = $1 AND episode_id = ANY($2::uuid[]) AND type = 'medication' AND med_name IS NOT NULL
ORDER BY episode_id, occurred_at DESC, id DESC
`

type LatestMedicationByEpisodesParams struct {
	FamilyID   uuid.UUID
	EpisodeIds []uuid.UUID
}

func (q *Queries) LatestMedicationByEpisodes(ctx context.Context, arg LatestMedicationByEpisodesParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, latestMedicationByEpisodes, arg.FamilyID, arg.EpisodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.MemberID,
			&i.EpisodeID,
			&i.Type,
			&i.OccurredAt,
			&i.Body,
			&i.IsFlare,
			&i.Severity,
			&i.Temperature,
			&i.MedName,
			&i.MedDose,
			&i.MedUnit,
			&i.CostCents,
			&i.Details,
			&i.SearchText,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestTemperatureByEpisodes = `-- name: LatestTemperatureByEpisodes :many
SELECT DISTINCT ON (episode_id) id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at FROM records
WHERE family_id = $1 AND episode_id = ANY($2::uuid[]) AND temperature IS NOT NULL
ORDER BY episode_id, occurred_at DESC, id DESC
`

type LatestTemperatureByEpisodesParams struct {
	FamilyID   uuid.UUID
	EpisodeIds []uuid.UUID
}

func (q *Queries) LatestTemperatureByEpisodes(ctx context.Context, arg LatestTemperatureByEpisodesParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, latestTemperatureByEpisodes, arg.FamilyID, arg.EpisodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.MemberID,
			&i.EpisodeID,
			&i.Type,
			&i.OccurredAt,
			&i.Body,
			&i.IsFlare,
			&i.Severity,
			&i.Temperature,
			&i.MedName,
			&i.MedDose,
			&i.MedUnit,
			&i.CostCents,
			&i.Details,
			&i.SearchText,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeRecordsAsc = `-- name: ListEpisodeRecordsAsc :many
SELECT id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at FROM records
WHERE family_id = $1 AND episode_id = $2
  AND ($3::timestamptz IS NULL OR occurred_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR occurred_at <= $4::timestamptz)
ORDER BY occurred_at, id
`

type ListEpisodeRecordsAscParams struct {
	FamilyID  uuid.UUID
	EpisodeID *uuid.UUID
	FromTime  *time.Time
	ToTime    *time.Time
}

func (q *Queries) ListEpisodeRecordsAsc(ctx context.Context, arg ListEpisodeRecordsAscParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, listEpisodeRecordsAsc,
		arg.FamilyID,
		arg.EpisodeID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.MemberID,
			&i.EpisodeID,
			&i.Type,
			&i.OccurredAt,
			&i.Body,
			&i.IsFlare,
			&i.Severity,
			&i.Temperature,
			&i.MedName,
			&i.MedDose,
			&i.MedUnit,
			&i.CostCents,
			&i.Details,
			&i.SearchText,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRecordsByMembers = `-- name: ListRecentRecordsByMembers :many
SELECT id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at FROM records
WHERE id IN (
    SELECT x.id FROM (
        SELECT r.id, row_number() OVER (PARTITION BY r.member_id ORDER BY r.occurred_at DESC, r.id DESC) AS rn
        FROM records r
        WHERE r.family_id = $1 AND r.member_id = ANY($2::uuid[])
    ) x WHERE x.rn <= $3::int
)
ORDER BY occurred_at DESC, id DESC
`

type ListRecentRecordsByMembersParams struct {
	FamilyID  uuid.UUID
	MemberIds []uuid.UUID
	PerMember int32
}

func (q *Queries) ListRecentRecordsByMembers(ctx context.Context, arg ListRecentRecordsByMembersParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, listRecentRecordsByMembers, arg.FamilyID, arg.MemberIds, arg.PerMember)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.MemberID,
			&i.EpisodeID,
			&i.Type,
			&i.OccurredAt,
			&i.Body,
			&i.IsFlare,
			&i.Severity,
			&i.Temperature,
			&i.MedName,
			&i.MedDose,
			&i.MedUnit,
			&i.CostCents,
			&i.Details,
			&i.SearchText,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordStorageKeys = `-- name: ListRecordStorageKeys :many
SELECT id, original_key, storage_key FROM attachments WHERE family_id = $1 AND record_id = $2
`

type ListRecordStorageKeysParams struct {
	FamilyID uuid.UUID
	RecordID *uuid.UUID
}

type ListRecordStorageKeysRow struct {
	ID          uuid.UUID
	OriginalKey string
	StorageKey  *string
}

func (q *Queries) ListRecordStorageKeys(ctx context.Context, arg ListRecordStorageKeysParams) ([]ListRecordStorageKeysRow, error) {
	rows, err := q.db.Query(ctx, listRecordStorageKeys, arg.FamilyID, arg.RecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordStorageKeysRow
	for rows.Next() {
		var i ListRecordStorageKeysRow
		if err := rows.Scan(&i.ID, &i.OriginalKey, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at FROM records r
WHERE r.family_id = $1
  AND ($2::uuid IS NULL OR r.member_id = $2::uuid)
  AND ($3::uuid IS NULL OR r.episode_id = $3::uuid)
  AND (NOT $4::boolean OR r.episode_id IS NULL)
  AND (cardinality($5::text[]) = 0 OR r.type::text = ANY($5::text[]))
  AND (NOT $6::boolean OR r.is_flare)
  AND ($7::timestamptz IS NULL OR r.occurred_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR r.occurred_at <= $8::timestamptz)
  AND ($9::text IS NULL OR r.search_text ILIKE $9::text)
  AND ($10::timestamptz IS NULL
       OR (r.occurred_at, r.id) < ($10::timestamptz, $11::uuid))
ORDER BY r.occurred_at DESC, r.id DESC
LIMIT $12
`

type ListRecordsParams struct {
	FamilyID   uuid.UUID
	MemberID   *uuid.UUID
	EpisodeID  *uuid.UUID
	InboxOnly  bool
	Types      []string
	FlareOnly  bool
	FromTime   *time.Time
	ToTime     *time.Time
	Pattern    *string
	CursorTime *time.Time
	CursorID   *uuid.UUID
	Lim        int32
}

func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, listRecords,
		arg.FamilyID,
		arg.MemberID,
		arg.EpisodeID,
		arg.InboxOnly,
		arg.Types,
		arg.FlareOnly,
		arg.FromTime,
		arg.ToTime,
		arg.Pattern,
		arg.CursorTime,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.MemberID,
			&i.EpisodeID,
			&i.Type,
			&i.OccurredAt,
			&i.Body,
			&i.IsFlare,
			&i.Severity,
			&i.Temperature,
			&i.MedName,
			&i.MedDose,
			&i.MedUnit,
			&i.CostCents,
			&i.Details,
			&i.SearchText,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsByIDsForUpdate = `-- name: ListRecordsByIDsForUpdate :many
SELECT id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at FROM records WHERE family_id = $1 AND id = ANY($2::uuid[]) FOR UPDATE
`

type ListRecordsByIDsForUpdateParams struct {
	FamilyID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) ListRecordsByIDsForUpdate(ctx context.Context, arg ListRecordsByIDsForUpdateParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, listRecordsByIDsForUpdate, arg.FamilyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.MemberID,
			&i.EpisodeID,
			&i.Type,
			&i.OccurredAt,
			&i.Body,
			&i.IsFlare,
			&i.Severity,
			&i.Temperature,
			&i.MedName,
			&i.MedDose,
			&i.MedUnit,
			&i.CostCents,
			&i.Details,
			&i.SearchText,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecordSearchText = `-- name: SetRecordSearchText :exec
UPDATE records SET search_text = $1, updated_at = now() WHERE family_id = $2 AND id = $3
`

type SetRecordSearchTextParams struct {
	SearchText string
	FamilyID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) SetRecordSearchText(ctx context.Context, arg SetRecordSearchTextParams) error {
	_, err := q.db.Exec(ctx, setRecordSearchText, arg.SearchText, arg.FamilyID, arg.ID)
	return err
}

const trendPoints = `-- name: TrendPoints :many
SELECT id, occurred_at, temperature, severity FROM records
WHERE family_id = $1 AND episode_id = $2
  AND (temperature IS NOT NULL OR severity IS NOT NULL)
  AND ($3::timestamptz IS NULL OR occurred_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR occurred_at <= $4::timestamptz)
ORDER BY occurred_at, id
`

type TrendPointsParams struct {
	FamilyID  uuid.UUID
	EpisodeID *uuid.UUID
	FromTime  *time.Time
	ToTime    *time.Time
}

type TrendPointsRow struct {
	ID          uuid.UUID
	OccurredAt  time.Time
	Temperature *float64
	Severity    *int16
}

func (q *Queries) TrendPoints(ctx context.Context, arg TrendPointsParams) ([]TrendPointsRow, error) {
	rows, err := q.db.Query(ctx, trendPoints,
		arg.FamilyID,
		arg.EpisodeID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrendPointsRow
	for rows.Next() {
		var i TrendPointsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Temperature,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecord = `-- name: UpdateRecord :one
UPDATE records SET
    member_id = $1,
    episode_id = $2,
    type = $3,
    occurred_at = $4,
    body = $5,
    is_flare = $6,
    severity = $7,
    temperature = $8,
    med_name = $9,
    med_dose = $10,
    med_unit = $11,
    cost_cents = $12,
    details = $13,
    search_text = $14,
    updated_at = now()
WHERE family_id = $15 AND id = $16
RETURNING id, family_id, member_id, episode_id, type, occurred_at, body, is_flare, severity, temperature, med_name, med_dose, med_unit, cost_cents, details, search_text, created_by, created_at, updated_at
`

type UpdateRecordParams struct {
	MemberID    uuid.UUID
	EpisodeID   *uuid.UUID
	Type        *RecordType
	OccurredAt  time.Time
	Body        string
	IsFlare     bool
	Severity    *int16
	Temperature *float64
	MedName     *string
	MedDose     *float64
	MedUnit     *string
	CostCents   *int32
	Details     []byte
	SearchText  string
	FamilyID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, updateRecord,
		arg.MemberID,
		arg.EpisodeID,
		arg.Type,
		arg.OccurredAt,
		arg.Body,
		arg.IsFlare,
		arg.Severity,
		arg.Temperature,
		arg.MedName,
		arg.MedDose,
		arg.MedUnit,
		arg.CostCents,
		arg.Details,
		arg.SearchText,
		arg.FamilyID,
		arg.ID,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.MemberID,
		&i.EpisodeID,
		&i.Type,
		&i.OccurredAt,
		&i.Body,
		&i.IsFlare,
		&i.Severity,
		&i.Temperature,
		&i.MedName,
		&i.MedDose,
		&i.MedUnit,
		&i.CostCents,
		&i.Details,
		&i.SearchText,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
